# Generated by Django 4.1.2 on 2023-03-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Popularplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="img")),
                ("title", models.CharField(max_length=50)),
                ("desc", models.TextField()),
            ],
            options={
                "verbose_name": "Popularplaces",
                "verbose_name_plural": "Popularplaces",
            },
        ),
    ]
