# Generated by Django 4.1.2 on 2023-03-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="popularplace",
            name="visible",
            field=models.BooleanField(default=False),
        ),
    ]
