# Generated by Django 4.1.2 on 2023-03-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0002_popularplace_visible"),
    ]

    operations = [
        migrations.CreateModel(
            name="Popularplace1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="img")),
                ("title", models.CharField(max_length=50)),
                ("desc", models.TextField()),
                ("visible", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Popularplace1",
                "verbose_name_plural": "Popularplace1",
            },
        ),
        migrations.AlterModelOptions(
            name="popularplace",
            options={
                "verbose_name": "Popularplace",
                "verbose_name_plural": "Popularplace",
            },
        ),
    ]
