# Generated by Django 4.1.2 on 2023-03-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0003_popularplace1_alter_popularplace_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("totaladults", models.IntegerField()),
            ],
            options={"verbose_name": "Booking", "verbose_name_plural": "Booking",},
        ),
    ]
