# Generated by Django 4.1.2 on 2023-03-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0004_booking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking", old_name="place", new_name="destination",
        ),
        migrations.AddField(
            model_name="booking",
            name="source",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
