# Generated by Django 4.1.2 on 2023-03-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0005_rename_place_booking_destination_booking_source"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking", old_name="destination", new_name="place",
        ),
        migrations.RemoveField(model_name="booking", name="source",),
    ]
